language: rust
rust:
  - stable
  - beta

dist: trusty
sudo: required

addons:
  apt:
    sources:
      - sourceline: ppa:myriadrf/drivers
    packages:
      - libsoapysdr-dev
      - llvm-3.9-dev
      - libclang-3.9-dev

before_script:
  - dpkg -l libsoapysdr-dev
  - dpkg -L libsoapysdr-dev

cache: cargo
